const quizzes = [

{
"name": "what-s-my-aesthetic",
"descr": "Wondering what your aesthetic is? Everyone has their own brand of beauty, so what is yours? Don't know? Time to take this quiz and find out once and for all.",
"title": "What's My Aesthetic?",
"url": "../what-s-my-aesthetic/index.html",
"image": "../what-s-my-aesthetic/what-s-my-aesthetic-small.jpg",
"author": "jenn",
"numberOfParts": 29,
"date": "2 years ago",
"segment": "women",
"tags": "beauty style fashion charm women"
    },
    {
"name": "am-i-in-love",
"descr": "Wondering if you really, truly are in love? Stop second-guessing and worrying! Just take this insightful quiz and put your overanalyzing aside for a change.",
"title": "Am I In Love?",
"url": "../am-i-in-love/index.html",
"image": "../am-i-in-love/am-i-in-love-small.jpg",
"author": "jenn",
"numberOfParts": 29,
"date": "2 years ago",
"segment": "relationship",
"tags": "women falling-in-love feelings relationship date"
},
{
"name": "animalPersonality",
"descr": "A few simple questions to find out which animal you are. It may surprise you a lot :).",
"title": "What Animal Are You?",
"url": "../animalPersonality/index.html",
"image": "../animalPersonality/animalPersonality-small.jpg",
"author": "",
"numberOfParts": 29,
"date": "6 years ago",
"segment": "animals",
"tags": "animal personality relationships teens"
},
{
"name": "what-type-of-person-are-you",
"descr": "What makes you you? Take our quiz and find out more about your personality.",
"title": "What Type Of Person Are You?",
"url": "../what-type-of-person-are-you/index.html",
"image": "../what-type-of-person-are-you/what-type-of-person-are-you-small.jpg",
"author": "",
"numberOfParts": 29,
"date": "5 years ago",
"segment": "personality",
"tags": "personality character-trait temper behavior attitude look appearance living lifestyle"
},
{
"name": "which-celebrity-are-you",
"descr": "Answer the questions, to find out which celebrity you're the most like!",
"title": "Which Celebrity Are You?",
"url": "../which-celebrity-are-you/index.html",
"image": "../which-celebrity-are-you/which-celebrity-are-you-small.jpg",
"author": "",
"numberOfParts": 29,
"date": "6 years ago",
"segment": "entertainment",
"tags": "show-biz man woman celebrity relationship star idol personality character-trait attitude"
},
{
"name": "predict-my-future",
"descr": "Want to know what's in store for you? Then take this quiz! Find out if the road you're on is the road you want to take or if it's time to take a different tack!",
"title": "Predict My Future!",
"url": "../predict-my-future/index.html",
"image": "../predict-my-future/predict-my-future-small.jpg",
"author": "jinny",
"numberOfParts": 29,
"date": "2 years ago",
"segment": "living",
"tags": "living future omen prophecy prediction"
},
{
"name": "fursona-generator",
"descr": "A fursona is a furry animal character that corresponds with your overall look, personality, and habits. This entertaining quiz will match you with your fursona!",
"title": "Fursona Generator",
"url": "../fursona-generator/index.html",
"image": "../fursona-generator/fursona-generator-small.jpg",
"author": "lyn",
"numberOfParts": 29,
"date": "2 years ago",
"segment": "personality",
"tags": "furry animal cosplay fursona spirit generator"
},
{
"name": "are-you-a-bad-person",
"descr": "Have you ever wondered if you were a bad person? We can help you figure it out once and for all. All you have to do is answer these simple questions truthfully.",
"title": "Are You A Bad Person?",
"url": "../are-you-a-bad-person/index.html",
"image": "../are-you-a-bad-person/are-you-a-bad-person-small.jpg",
"author": "shannon",
"numberOfParts": 29,
"date": "2 years ago",
"segment": "personality",
"tags": "lifestyle personality character-trait attitude bad-character behavior temper relationship"
},
{
"name": "what-fetish-do-you-secretly-have",
"descr": "A mellow quiz that will ask questions that make you feel comfy in order to be able to reveal your secret fetish. Everyone has something that makes them feel warm and bubbly on the inside, rather it be a warm brownie drizzled in fudge or beautiful spiral curls in someones hair.",
"title": "What Fetish Do You Secretly Have?",
"url": "../what-fetish-do-you-secretly-have/index.html",
"image": "../what-fetish-do-you-secretly-have/what-fetish-do-you-secretly-have-small.jpg",
"author": "eugenia",
"numberOfParts": 29,
"date": "2 years ago",
"segment": "personality",
"tags": "relationship love behavior attitude attraction psychology look appearance man woman personality fetish"
},
{
"name": "am-i-a-furry",
"descr": "Are you someone that has an enthusiasm for animal characters that also have human characteristics? Find out if you are dedicated enough to be considered a furry!",
"title": "Am I A Furry?",
"url": "../am-i-a-furry/index.html",
"image": "../am-i-a-furry/am-i-a-furry-small.jpg",
"author": "shannon",
"numberOfParts": 29,
"date": "2 years ago",
"segment": "entertainment",
"tags": "entertainment furry animal character costume avatar"
},
{
"name": "do-i-love-him",
"descr": "Maybe you do, maybe you don't, how do you really know if you are in love? Answer the following questions and reveal your true feelings about this man in your life.",
"title": "Do I Love Him?",
"url": "../do-i-love-him/index.html",
"image": "../do-i-love-him/do-i-love-him-small.jpg",
"author": "danielle",
"numberOfParts": 29,
"date": "2 years ago",
"segment": "women",
"tags": "women men relationship feeling love"
},
{
"name": "anime-name-generator",
"descr": "Every true anime fan needs an anime name! But not just any name will do. Your anime name should represent your character and personality. This fun quiz will isolate your dominant characteristics to assign you the most amazing anime name! What are you waiting for? Let's begin the online quiz right now!",
"title": "Anime Name Generator",
"url": "../anime-name-generator/index.html",
"image": "../anime-name-generator/anime-name-generator-small.jpg",
"author": "lyn",
"numberOfParts": 29,
"date": "2 years ago",
"segment": "living",
"tags": "anime name generator character feature"
},
{
"name": "are-you-a-top-or-a-bottom",
"descr": "Wondering if you're a top or a bottom? Then it's about time you took a quiz that'll tell it like it is, no sugar coating! Maybe having some insight might explain a few things.",
"title": "Are You A Top Or A Bottom?",
"url": "../are-you-a-top-or-a-bottom/index.html",
"image": "../are-you-a-top-or-a-bottom/are-you-a-top-or-a-bottom-small.jpg",
"author": "jenn",
"numberOfParts": 29,
"date": "1 year ago",
"segment": "couples",
"tags": "men women sex love personality"
},
{
"name": "how-well-do-you-know-yourself",
"descr": "Do you know your own mind? Do you know if something would look good on you without having to try it on? When was the last time you knew when something was beyond your limits?",
"title": "How Well Do You Know Yourself?",
"url": "../how-well-do-you-know-yourself/index.html",
"image": "../how-well-do-you-know-yourself/how-well-do-you-know-yourself-small.jpg",
"author": "naomi",
"numberOfParts": 29,
"date": "6 years ago",
"segment": "personality",
"tags": "personality psychology self-knowledge mind"
},
{
"name": "drawing-idea-generator",
"descr": "If you want to draw something, but you are out of good ideas for subjects, this fun online quiz is just the ticket! Answer the brief questions for a custom recommendation.",
"title": "Drawing Idea Generator",
"url": "../drawing-idea-generator/index.html",
"image": "../drawing-idea-generator/drawing-idea-generator-small.jpg",
"author": "lyn",
"numberOfParts": 7,
"date": "2 years ago",
"segment": "hobby",
"tags": "art draw drawing idea generator"
},
{
"name": "which-us-state-should-you-live-in",
"descr": "Which state fits your state of mind?",
"title": "Which U.S. State Should You Live In?",
"url": "../which-us-state-should-you-live-in/index.html",
"image": "../which-us-state-should-you-live-in/which-us-state-should-you-live-in-small.jpg",
"author": "",
"numberOfParts": 29,
"date": "6 years ago",
"segment": "living",
"tags": "usa living location us-geography"
},
{
"name": "what-is-your-guardian-angels-name",
"descr": "Ever wondered what your guardian angel's name is? Find out now!",
"title": "What Is Your Guardian Angel's Name?",
"url": "../what-is-your-guardian-angels-name/index.html",
"image": "../what-is-your-guardian-angels-name/what-is-your-guardian-angels-name-small.jpg",
"author": "jenifer",
"numberOfParts": 29,
"date": "3 years ago",
"segment": "women",
"tags": "guardian name angel"
},
{
"name": "what-is-wrong-with-me",
"descr": "Do you feel like something is off about you and your life, but can't figure out what? If so take this quiz, and we can help you discover what it is that your missing and need to improve on in your life!",
"title": "What Is Wrong With Me?",
"url": "../what-is-wrong-with-me/index.html",
"image": "../what-is-wrong-with-me/what-is-wrong-with-me-small.jpg",
"author": "danielle",
"numberOfParts": 29,
"date": "1 year ago",
"segment": "living",
"tags": "problem living missing family life"
},
{
"name": "am-i-in-love-with-my-best-friend",
"descr": "Do you have a special person in your life that you've always only thought of as a friend, but now things are changing leaving you wondering if you're falling in love with your best friend? Find out if it's true by taking this quiz!",
"title": "Am I In Love With My Best Friend?",
"url": "../am-i-in-love-with-my-best-friend/index.html",
"image": "../am-i-in-love-with-my-best-friend/am-i-in-love-with-my-best-friend-small.jpg",
"author": "shannon",
"numberOfParts": 29,
"date": "1 year ago",
"segment": "relationship",
"tags": "relationship friends love besties romance BFF partners friendship"
},
{
"name": "users-quizzes/are-you-a-good-person-2",
"descr": "Have you ever wondered if you are an ideal friend or just plain mean? This quiz will let you know if you should correct your ways or just stay the same!",
"title": "Are You A Good Person? No. 2",
"url": "../users-quizzes/are-you-a-good-person-2/index.html",
"image": "../users-quizzes/are-you-a-good-person-2/are-you-a-good-person-2-small.jpg",
"author": "hi1234",
"numberOfParts": 14,
"date": "1 year ago",
"segment": "personality",
"tags": "good person god kind ideal friend"
},
{
"name": "what-is-my-type",
"descr": "A fun quiz that will help you figure out what your type is. There are so many different personalities that can match perfectly together, whereas certain types wouldn't ever make it together no matter what.",
"title": "What Is My Type?",
"url": "../what-is-my-type/index.html",
"image": "../what-is-my-type/what-is-my-type-small.jpg",
"author": "eugenia",
"numberOfParts": 29,
"date": "2 years ago",
"segment": "personality",
"tags": "boy girl compatible relationship friend"
},
{
"name": "who-is-your-true-friend",
"descr": "You might have a lot of friends in your life, or people that are pretending to be your friends. Find out who your true friend is after you take this quick quiz!",
"title": "Who Is Your True Friend?",
"url": "../who-is-your-true-friend/index.html",
"image": "../who-is-your-true-friend/who-is-your-true-friend-small.jpg",
"author": "shannon",
"numberOfParts": 29,
"date": "2 years ago",
"segment": "relationship",
"tags": "relationship friends friendship companion intimate"
}];


